### ISSUE TITLE
CCRichLabelTTF->setOpacity没有效果

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#16]

**Comment by zcgit** [comment]
解决了，需要设置setVector

**Comment by stubma** [comment]
确实没作用, 设置setVector也没作用, 你怎么能行的? 我看了一下, 渲染时候的参数没错, 目前没明白问题在哪里

**Comment by zcgit** [comment]
我是设置了setVector(CCPointZero);你是这样的吗？

**Comment by zcgit** [comment]
我把构造函数改成：
CCGradientSprite::CCGradientSprite() :
        m_startColor(ccWHITE),
        m_endColor(ccWHITE),
        m_cEndOpacity(0),
        m_cStartOpacity(255),
        m_AlongVector(ccp(0, 0)),//这行就是改的，原来是cpp(0,1)
        m_bCompressedInterpolation(true) {
}

**Comment by stubma** [comment]
(0, 1)不应该有影响, 暂时没空看这个问题, 先放着

**Comment by zcgit** [comment]
我看源码是CCGradientSprite的219行：
float h = ccpLength(m_AlongVector);
如果我把 h = 0，
就ok了。
