### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by xuepomh** [stubma/cocos2dx-better#2]
Hi,I built the code in XCode,but some erros appeared as follow:
In file included from /Users/apple/Documents/project_cocos2dx/TestDemo/cocos2dx-common/cocos2dx-common/src/CCAssetInputStream.cpp:26:
In file included from /Users/apple/Documents/project_cocos2dx/TestDemo/cocos2dx-common/cocos2dx-common/include/CCMoreMacros.h:47:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:409:1: error: expected unqualified-id
@class NSString, Protocol;
^

**Comment by stubma** [comment]
Compile source as 改成objective-c++
