### ISSUE TITLE
关于link的小问题

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#24]
我看到您在label里面加了CCMenu，这样会不会有点击权限的问题？而且我感觉CCMenu设计的很不好。
        我目前的做法是单独继承自您的label，然后在里面让其继承于CCTouchDelegate,这样label其实就可以支持点击了，这时候就可以设置点击事件的回调。至于link，可能就得判断点击位置是不是在label的指定区域，如果在，那么就回调link事件。这样设计的好处是，去掉了CCMenu，不用创建menuitem了。但是又引入了CCTouchDelegate。
       其实用CCMenu也ok，但是点击权限不知道好不好控制。

**Comment by stubma** [comment]
ccmenu没感觉有啥问题, 一直用的很好呃. 要设置权限CCRichLabelTTF加个方法设置menu的priority就可以了
