### ISSUE TITLE
link最好支持userobject

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#25]
这样更好用，每个link带一个userobject，这样，回调的时候可以准确的判断是哪个link了。
而且，目前的link不支持换行，例如我setDimensions后，就无法支持了。

**Comment by stubma** [comment]
换行demo里测试没问题, 什么情况不支持?

**Comment by stubma** [comment]
setLinkTarget的时候可以用CCCallFuncO附带额外对象

**Comment by stubma** [comment]
没有更多反馈了? 那我关掉了.
