### ISSUE TITLE
demo跑不起来... cocos2d-x-2.2

### ISSUE THREAD

**Issue by Jowyer** [stubma/cocos2dx-better#27]
我是cocos2dx新手，下载了您的开源工程，参照README把工程目录放到和"cocos2d-x"同一个父目录下，但是TestCpp跑不起来。
报错信息为：
Undefined symbols for architecture i386:
  "CocosDenshion::SimpleAudioEngine::sharedEngine()", referenced from:
      cocos2d::CCResourceLoader::CDMusicTask::load() in libcocos2dxcommon.a(CCResourceLoader.o)
      cocos2d::CCResourceLoader::CDEffectTask::load() in libcocos2dxcommon.a(CCResourceLoader.o)
  "CocosDenshion::SimpleAudioEngine::preloadEffect(char const_)", referenced from:
      cocos2d::CCResourceLoader::CDEffectTask::load() in libcocos2dxcommon.a(CCResourceLoader.o)
  "CocosDenshion::SimpleAudioEngine::preloadBackgroundMusic(char const_)", referenced from:
      cocos2d::CCResourceLoader::CDMusicTask::load() in libcocos2dxcommon.a(CCResourceLoader.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

重新把cocos2dx-common的项目文件拖进去依旧报此错误。
是不是静态库的依赖我设置的不对啊？恳请不吝赐教！

**Comment by stubma** [comment]
cocos2d-x和CocosDenshion的ios工程设置有个地方不对, 必须把这两个工程里的architectures和valid architectures恢复为默认值
![2013-11-05 19 26 10](https://f.cloud.github.com/assets/818850/1472946/391865c0-460d-11e3-889f-7eab12a395ea.png)
![2013-11-05 19 26 27](https://f.cloud.github.com/assets/818850/1472947/3918bb42-460d-11e3-80e6-216b0f50e10b.png)
![2013-11-05 19 26 20](https://f.cloud.github.com/assets/818850/1472948/391921c2-460d-11e3-952e-87343430147c.png)

**Comment by JoHuang** [comment]
hi there,

TestCpp is only built successfully for device, not Simulator. Whether I change the "architectures和valid architectures" or not. Still got "ld: symbol(s) not found for architecture i386".

In addition, if I commented the SimpleAudioEngine code, It works on simulator.

void CCResourceLoader::CDMusicTask::load() {
    //SimpleAudioEngine::sharedEngine()->preloadBackgroundMusic(name.c_str());
}

void CCResourceLoader::CDEffectTask::load() {
    //SimpleAudioEngine::sharedEngine()->preloadEffect(name.c_str());
}

Please help. 

Thanks a lot!

**Comment by JoHuang** [comment]
One more experiment:

I can even delete CocsDenshion project in Framework Group of cocos2dxcommon project, and it still work on device.

Can't figure out why...

**Comment by stubma** [comment]
我更新了一下, 你重新试试吧, 应该改好了.
