### ISSUE TITLE
设置颜色

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#28]
label设置颜色后，图标也会变成该颜色，例如我将字设置成黑色，图标也就变黑了。

**Comment by stubma** [comment]
你是说CCRichLabelTTF? 我在demo里设置setFontFillColor(ccBlack)没有看到图片变黑

**Comment by zcgit** [comment]
setColor就会吧，而且我还发现一个，就是在android平台上，文字中的图标并没有根据屏幕自动拉升，所以会导致在分辨率高的手机上感觉图片特别小，我试着按比例放大，好像也不行，不知道你怎么解决。

**Comment by stubma** [comment]
CCLabelTTF, CCRichLabelTTF都是用setFontFillColor设置颜色的
