### ISSUE TITLE
 CCImage_richlabel_ios.mm line 610 CCImage & CCImage undeclared

### ISSUE THREAD

**Issue by jiadeZhang** [stubma/cocos2dx-better#30]
I compile it in mac,xcode 5.0.2  and i got the error

file :  CCImage_richlabel_ios.mm

static bool _initWithString(const char \* pText, CCImage::ETextAlign eAlign, const char \* pFontName, int nSize, tImageInfo\* pInfo, CCPoint\* outShadowStrokePadding, LinkMetaList\* linkMetas) {
    bool bRet = false;

error info :
Semantic issue Use of undeclared Identifier 'CCImage'; did you mean 'CGImage'

and then I add #include "CCImage.h" #include "CCGemetry.h" in the head!
but it got same error! why?
I am new in mac programming, and this is first time i'am using mac machine!
somebody help me!

**Comment by jiadeZhang** [comment]
没想到是国人写的，再说清楚点，
我对mac的开发环境不是很熟悉，今天刚开始接触，我不清楚是否还需要设置什么
大部分问题已经解决了，就还有这个，我不知道为什么。

**Comment by jiadeZhang** [comment]
刚把它编过了，是行1117的NS_CC_BEGIN 名称空间引起的。
在改成
static bool _initWithString(const char \* pText, cocos2d::CCImage::ETextAlign eAlign, const char \* pFontName, int nSize, tImageInfo\* pInfo, cocos2d::CCPoint\* outShadowStrokePadding, LinkMetaList\* linkMetas) {
bool bRet = false;
编译通过~

**Comment by stubma** [comment]
只是提示找不到CCImage， 你可能没clone cocos2d-x, cocos2d-x的代码需要和cocos2dx-common处于同一个目录中

**Comment by jiadeZhang** [comment]
我把您的代码加入到cocos2dx-2.2工程中的，所以应该不是找不到文件的问题。
在CCImage前加上cocos2d::空间限定就没问题了
我不确定是不是bug？

**Comment by stubma** [comment]
这些代码都在cocos2d空间里, 不需要指定, 你碰到这些问题只属于你工程设置问题. 对我代码的改动都是不必要的, 是因为你设置问题引起的, 等到你熟悉了环境你自然就会理解为啥会这样. 现阶段你能编译过去就行了, 只要不改动实际逻辑, 加个什么空间前缀的没关系.

**Comment by jiadeZhang** [comment]
hi，stubma
当然，不改动就能很好的运行。我改动他是因为在项目能更方便的使用。
谢谢，这个功能真的很棒，省了我很多功夫。
再次谢谢您。
