### ISSUE TITLE
One suggestion

### ISSUE THREAD

**Issue by oOEdoOo** [stubma/cocos2dx-better#33]
![image](https://f.cloud.github.com/assets/1826701/1699936/2cf4eca0-5fda-11e3-821e-0fd249ce671d.png)

put these import statments into .mm file will be better~

**Comment by stubma** [comment]
why?

**Comment by JoHuang** [comment]
When I drag the cocos2dx-better.project to my app project, and set the correct include header include path,
I got obj-c related issues.

![screen shot 2013-12-09 at 6 57 40 pm](https://f.cloud.github.com/assets/4118159/1704028/d39398c2-60c0-11e3-985d-0c1dc1d9b38a.png)

I guess it's related to this import issue. So I just commented the 2 import lines suggested by oOEdoOo.
And then still got link issues.

![screen shot 2013-12-09 at 7 06 36 pm](https://f.cloud.github.com/assets/4118159/1704090/05276430-60c2-11e3-940a-0fff52c11405.png)

But the TestCpp works fine.
Any steps I missed?

Thanks a lot!

**Comment by stubma** [comment]
![2013-12-09 19 19 48](https://f.cloud.github.com/assets/818850/1704161/d8766786-60c3-11e3-89d2-36503f1dbdb4.png)

change compile source as to objective-c++

**Comment by JoHuang** [comment]
But this setting cause my pure c library compiled fail.
Is the setting too aggressive?
Is there any particular reason to set this instead of default setting?
the original Cocos2d-x test cpp app doesn't need this.

Sorry that I have many questions...
BTW, is it possible just dragging few files related to the component I need  instead of the whole project?
Might get more compatible?

**Comment by stubma** [comment]
add "-x c" flag to your c source file. in build phase source list, double click a source file

**Comment by stubma** [comment]
or create a new target for your c library

**Comment by oOEdoOo** [comment]
Sry for reply late.
JoHuang's problem has explained why. Exactly I encounter the same problem as him. 
When I dragged the project into my project, Many c library compiled fail. 

So I just drag the CCRichLabel related files into my project since CCRichLabel is what I need, and commented the 2 objective-c statement in .h file. Everything works.

I think move all the objective-c code into .mm file will make this library much easier to be integrated, since no need to modify the project setting or code compile type.

**Comment by stubma** [comment]
some macro is not easy to be refactored out as a .mm file. creating new target for your c library is best solution.
