### ISSUE TITLE
iOS project Target Dependency

### ISSUE THREAD

**Issue by JoHuang** [stubma/cocos2dx-better#34]
![screen shot 2013-12-09 at 6 38 33 pm](https://f.cloud.github.com/assets/4118159/1703930/08fb3a9e-60bf-11e3-92d1-05174710bd70.png)

It's better to add target dependency to let Xcode compile sub-project automatically.

Test cpp as well.

Thanks for great work!

**Comment by stubma** [comment]
ok, added
