### ISSUE TITLE
在android上label还是会有纹理丢失的问题。

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#36]
一般是跳转到某些activity才会出现该问题，加上了reloadAll还是会出现。

**Comment by stubma** [comment]
重现不了, 你贴个例子. 我倒是奇怪现在跳转到其它activity surface不销毁了, 难道啥时候android改了

**Comment by zcgit** [comment]
不是不销毁，而是在重写GLSurfaceView的onPause()方法的时候不去调用super.onPause();这样确实能实现想要的效果，但是就不敢确定所有机器是否都ok，还有我好像在哪记得android现在有个参数是设置这块的，但是没有找到。

**Comment by stubma** [comment]
改成调用onPause, reloadAll被执行, 贴图恢复正常, 把链接点击改成打开浏览器, 退回demo, 正常. 重现不了你说的问题

**Comment by stubma** [comment]
无后续反馈, 关闭
