### ISSUE TITLE
CCRichLabel ,显示不出来

### ISSUE THREAD

**Issue by lixiaobing** [stubma/cocos2dx-better#41]
我是这样写的：
CCRichLabelTTF\* pRichLab = CCRichLabelTTF::create("Hell[color=ffff0000]o[/color]", "Arial", TITLE_FONT_SIZE);
    pRichLab->setPosition(ccp(origin.x + visibleSize.width/2, origin.y + 100));
    pRichLab->setColor(ccBLUE);
    this->addChild(pRichLab, 10);

**Comment by stubma** [comment]
CCRichLabelTTF设置整体颜色要用setFontFillColor. 其它的没啥问题, 你放到demo里试试. richlabel绝对没问题, 我天天自己也要用. 另外代码要记得更新, 这两天调整了一下目录结构
