### ISSUE TITLE
get embedded image bound

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#43]
什么时候需要get embedded image bound，不明白加这个的用途。

**Comment by stubma** [comment]
当你需要做一些动态效果的时候, 比如你想在richlabel里嵌入个动画进去, 用现在的tag去描述是比较麻烦的, 新加一个tag去描述也麻烦, 所以这个时候, 你可以在label里面放一个空的image, 先留出来位置. 然后创建一个sprite去播放这个动画, 把这个sprite放到image的位置上去, 看上去就好像label能支持内嵌动画一样. demo已经做了修改, grossini有个上下浮动的效果, 这种情况能知道image bound就非常有用了.

**Comment by zcgit** [comment]
好主意。
   最近发现了一个ext，https://github.com/happykevins/cocos2dx-ext 他这个用的freetype实现的，不过貌似有点复杂，而且很久没维护，我看是renren做的？

**Comment by stubma** [comment]
我看过这个, 优点是有跨更多平台的可能, 缺点是引入了freetype库, 不好维护. 这些古老的开源库的代码风格我都不喜欢, 有什么问题想改就太累了.
