### ISSUE TITLE
crash after setLinkTarget

### ISSUE THREAD

**Issue by nealzxc** [stubma/cocos2dx-better#44]
setLinkTarget not stable enough,crash on : 
function : extractLinkMeta

 CGFloat startOffsetX = CTLineGetOffsetForStringIndex(line, linkStart, NULL) / CC_CONTENT_SCALE_FACTOR();

EXC_BAD_ACCESS

Even Just Use Link Tag Will Crash On IOS.

Just Test With: [link bg=3f7f7f7f bg_click=9fffff00]显示[/link]

Crash, Not Crash,Crash,Not Crash,I am crazy....

**Comment by zcgit** [comment]
maybe you should change to  [link bg=0x3f7f7f7f bg_click=0x9fffff00]显示[/link]

**Comment by stubma** [comment]
thanks, a bug only when there is one line and one link tag. fixed
