### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nealzxc** [stubma/cocos2dx-better#45]
Change The Font File On IOS, CRASH AGAIN!

Just Test With TTF File:http://pan.baidu.com/share/link?shareid=3476960079&uk=2014516696

change name to yahei.ttf, copy toe font dir.
Test with：
    CCRichLabelTTF\* label = CCRichLabelTTF::create("[font=font/yahei.ttf][color=ffffffff]W[/color]orld![/font]", "Helvetica",  30);

Crash, File :CCImage_richlabel.mm
        if(frame)
            CFRelease(frame);

YOU SHOULD TEST THE LIB DEEPLY ENOUGH.

**Comment by stubma** [comment]
别改文件名字, 保持微软雅黑.ttf试一下

**Comment by nealzxc** [comment]
一样的问题，貌似是和文件名字有关系，如果将你测试中的ttf文件名改了，也会出现crash。
我将名字修改为微软雅黑.ttf一样的问题。

**Comment by l8g** [comment]
改成这个吧

MicrosoftYaHei.ttf

这是字体的PostScript名称。

查看字体的PostScript名称的方法，Mac
1. 安装，
2. 打开字体册，选中字体
3. 点那个叹号
就能看到了

在 2014年5月7日，13:54，Neal notifications@github.com 写道：

**Comment by stubma** [comment]
thanks I8g.

@nealzxc: cocos2d-x ios上用ttf你得用正确的字体名, 所以demo的字体你改了也不行, 必须叫那个. 要你不要改文件名就是这个意思, 只不过我说错了, 名字不是叫"微软雅黑", 而是"MicrosoftYaHei", Microsoft和YaHei之前貌似有个空格, 我看到的是有个空格, 你都试试吧.

**Comment by nealzxc** [comment]
我试了一下，用post名称 用post中的唯一名称，都会出错。你们可以下一个微软雅黑的字体包试试，几个名称我豆试过了，结果一样。

**Comment by stubma** [comment]
第三方字体需要在plist里面添加描述

```
    <key>UIAppFonts</key>
    <array>
        <string>font/Microsoft YaHei.ttf</string>
    </array>
```

你可能会问demo的字体为啥不需要，应该是要的，但是不要确实也没事所以我也没加了, 为什么他比较特殊我不懂了，也许系统里已经有过了或者什么的。
