### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nealzxc** [stubma/cocos2dx-better#46]
你们竟然如此害怕出现问题？没有验证之下，就关闭一个issue？
字体文件：
![64beb673-01e0-4534-a957-a70e55c691cf](https://cloud.githubusercontent.com/assets/5086890/2900995/f70f1c62-d5ce-11e3-9d7a-71028dc1bfab.png)

Post名称：
![8158fe4e-582f-4fbd-9e01-c6ceca982701](https://cloud.githubusercontent.com/assets/5086890/2900972/9f613fcc-d5ce-11e3-83cf-f3af61d322b6.png)

代码段：
![64b149af-9a4f-4af3-bc53-f2b4f6bad0d5](https://cloud.githubusercontent.com/assets/5086890/2900981/c3426f42-d5ce-11e3-893a-47a9a66ebcca.png)

Crash:
![465a3551-446d-4f7b-abeb-9a6050d5e399](https://cloud.githubusercontent.com/assets/5086890/2901003/2eddb9aa-d5cf-11e3-8503-093c870d2d6b.png)

**Comment by stubma** [comment]
ios里面使用字体需要在plist里面添加ttf:

```
    <key>UIAppFonts</key>
    <array>
        <string>font/Microsoft YaHei.ttf</string>
    </array>
```

年轻人， 别那么武断下结论好吧。

**Comment by nealzxc** [comment]
问题解决，最明显的一步竟然是被忽略的一步，不好意思，是我武断了。
