### ISSUE TITLE
memory leaks on Android !

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-better#47]
我做了个测试，创建一千个CClabelTTF，内存会上涨再下降到原来状态，但是CCRichLabelTTF就不会下降到理想状态，初步判断，android端的实现有内存泄漏的问题，具体原因我正在查找，待会晚上看看能不能找到原因。

**Comment by stubma** [comment]
差多少？你还要看是否一直递增. 
android端，如果内嵌了atlas中的图片，最后一张atlas是有一个Bitmap一直缓存着的。CLBitmapDC是一个单例共享的，也是一直会在的

**Comment by zcgit** [comment]
没用atlas，我这测试会一直涨，正在排查。

**Comment by stubma** [comment]
关闭的时候至少写个结论

**Comment by zcgit** [comment]
OK, i pull 了一个requet，具体的你可以看下我加的注释。

**Comment by stubma** [comment]
thanks, 改的很对, 确实不应该retain

**Comment by zcgit** [comment]
找的好幸苦。。。最后排查到label里，其实ios也有，我之前一直以为只有android。
