### ISSUE TITLE
Android平台文字颜色问题

### ISSUE THREAD

**Issue by nealzxc** [stubma/cocos2dx-better#49]
[color=ffff0000]红色[/color] 现实出来是白色文字，几乎没有红色痕迹。[color=ff0000ff]蓝色[/color]显示出来时蓝色，什么原因？

**Comment by stubma** [comment]
demo的label按照你的改了一下

```
    // English, Chinese, color, font, overall test
    CCRichLabelTTF* label = CCRichLabelTTF::create("[color=ffff0000]红色[/color]",
                                                   "Helvetica",
                                                   30);
//  label->enableStroke(ccBLUE, 0.5f);
    label->setPosition(ccp(origin.x + visibleSize.width / 2,
                           origin.y + visibleSize.height / 5));
//  label->enableShadow(CCSizeMake(-10, -10), 0xafffff00, 4);
    label->setFontFillColor(ccc3(179, 179, 179));
    addChild(label);
```

android上测试没有问题, 是红色. demo的背景色自己改一下，背景缺省是红的。
![device-2014-05-24-121200](https://cloud.githubusercontent.com/assets/818850/3073642/9e15ccd6-e2f9-11e3-97f9-3c7f085359e7.png)

**Comment by stubma** [comment]
你要是觉得有问题，不用重新开bug，我reopen就行，先关了

**Comment by nealzxc** [comment]
需要别的地方有什么配置吗？比如manifest之类的地方？我打印了一下，解析得到的颜色值的确是对的。

**Comment by stubma** [comment]
android端有些java代码是必须要包含进来的, Android.mk里面也要正确引用module。一看README.md, 二看demo
