### ISSUE TITLE
希望能将wi的filter系统port到cocos2d-x

### ISSUE THREAD

**Issue by sixian** [stubma/cocos2dx-better#9]
如题

**Comment by stubma** [comment]
对于wiengine的特色功能, 如果可以做到不修改cocos2dx代码, 我就可以方便的移植过去. 但是filter是一个较为底层的功能, 不修改cocos2dx代码估计是不太可能的, 这会很麻烦, 因为如果cocos2dx更新了, merge的成本就可能很高. 所以目前还不会移植这个模块.

**Comment by sixian** [comment]
这真是太可惜了,如果能做成外挂插件的形式就最好了.怎么都好感谢你的回复和代码! CCRichLabelTTF找了很久真的很有用!

**Comment by zcgit** [comment]
这个是什么功能，没用过wi，同样感谢提供CCRichLabelTTF，很不错。

**Comment by stubma** [comment]
相当于photoshop里的滤镜, 用于对贴图提供动态修改功能. 具体可以看wiengine的demo/Other/Color Filter

**Comment by zcgit** [comment]
这个是不是可以做到那种把贴图里的某个颜色抽掉？例如把所有黑色背景去掉。

**Comment by stubma** [comment]
是的, 可以, demo里也有演示

**Comment by stubma** [comment]
颜色替换, 高亮, 浮雕, 灰度, 反正滤镜嘛, 只要你能做就能有什么效果. 不过其实, filter系统在opengles 2.0里可以用shader替代了, 所以, 不移植也没什么.
